# Generated by Django 5.0 on 2024-01-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField(null=True)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=64, null=True)),
                ('location', models.CharField(max_length=64, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.employee')),
            ],
        ),
    ]
