version: "3"
 
services:
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: "nithisha"
  #     POSTGRES_PASSWORD: "postgres"
  #     POSTGRES_DB: "userdatabase"
  #   ports:
  #     - "5432:5432"

  app1:
    container_name: iam1
    build:
      context: .
    ports:
      - "8001:8000"
    
 

  app2:
    container_name: iam2
    build:
      context: .
    ports:
      - "8002:8000"
    
 
  app3:
    container_name: iam3
    build:
      context: .
    ports:
      - "8003:8000"
    
    
 
  app4:
    container_name: iam4
    build:
      context: .
    ports:
      - "8004:8000"
    
    
        
 
  app5:
    container_name: iam5
    build:
      context: .
    ports:
      - "8005:8000"
    
  
  kong:
    image: kong/kong:latest
    container_name: kong
    environment:
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_DATABASE: "off"  # Disabling Kong's database
    ports:
      - "8000:8000"  # Kong proxy port
      - "8443:8443"  # Kong HTTPS proxy port
      - "8006:8001"  # Kong Admin API port
      - "8444:8444"  # Kong HTTPS Admin API port
    depends_on:
      - app1 
      - app2
      - app3
      - app4
      - app5 
    volumes:
      - ./kong.conf:/etc/kong/kong.conf:ro
  # kong:
  #   image: kong/kong:latest
  #   container_name: kong
  #   environment:
      
  #     KONG_DATABASE: "postgres"
  #     KONG_PG_HOST: "postgres"
  #     KONG_PG_USER: "nithisha"
  #     KONG_PG_PASSWORD: "postgres"
  #     KONG_PG_DATABASE: "userdatabase"
  #   ports:
  #     - "8000:8000"  # Kong proxy port
  #     - "8443:8443"  # Kong HTTPS proxy port
  #     - "8006:8001"  # Kong Admin API port
  #     - "8444:8444"  # Kong HTTPS Admin API port
  #   depends_on:
      
  
  

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    ports:
      - "80:80"  
    depends_on:
      - app1 
      - app2
      - app3
      - app4
      - app5
      - kong

