# Generated by Django 4.2.7 on 2024-01-06 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_unque_number',
            new_name='product_unique_number',
        ),
    ]
