# Generated by Django 4.2.7 on 2024-01-06 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_costprice_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingstock',
            name='prodcut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='api.product'),
        ),
    ]
