# Generated by Django 4.2.7 on 2024-01-08 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='current_stock',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
