# Generated by Django 4.2.7 on 2024-01-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_stock_current_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
