# Generated by Django 4.2.7 on 2024-01-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_stock_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='purchase_order',
            new_name='purchase_stock',
        ),
    ]
