# Generated by Django 4.2.7 on 2024-01-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_purchase_order_purchaseorder_purchase_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchase_stock',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='sales_stock',
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(default='super', max_length=250),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.CreateModel(
            name='SSOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='PPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchaseorder')),
            ],
        ),
    ]
