# Generated by Django 4.2.7 on 2024-01-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_purchaseorder_purchase_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppos',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='ssos',
            old_name='quantity',
            new_name='stock',
        ),
    ]
