# Generated by Django 4.2.7 on 2024-01-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_quantity_ppos_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
