# Generated by Django 4.2.7 on 2024-01-09 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_stock_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalStockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('product_unique_number', models.CharField(max_length=250, unique=True)),
                ('oenping_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchasestock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salestock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalstock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product')),
            ],
        ),
    ]
