# Generated by Django 4.2.7 on 2024-01-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_finalstockreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchase_orders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_orders',
        ),
    ]
