# Generated by Django 4.2.7 on 2024-01-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_product_purchase_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalstockreport',
            name='product_unique_number',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
