# Generated by Django 4.2.7 on 2024-01-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_finalstockreport_product_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalstockreport',
            name='oenping_stock',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finalstockreport',
            name='purchasestock',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finalstockreport',
            name='salestock',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finalstockreport',
            name='totalstock',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
