# Generated by Django 4.2.7 on 2024-01-10 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_finalstockreport_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalstockreport',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_stock', to='api.product'),
        ),
    ]
