# Generated by Django 4.2.6 on 2024-02-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TripApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="created_by",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="updated_by",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_by",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="updated_by",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="trip",
            name="created_by",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="updated_by",
            field=models.CharField(default="", max_length=250),
        ),
    ]
