# Generated by Django 4.2.6 on 2024-02-04 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "TripApp",
            "0002_alter_expenses_created_by_alter_expenses_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="member",
            new_name="trip",
        ),
    ]
