# Generated by Django 4.2.3 on 2024-01-06 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catogory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='cost',
            old_name='Cost',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='openingstock',
        ),
        migrations.AddField(
            model_name='cost',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
