# Generated by Django 4.2.3 on 2024-01-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_catogory_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
