# Generated by Django 4.2.4 on 2024-01-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_stock_openingstock_alter_stock_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='description',
        ),
    ]
