# Generated by Django 4.2.4 on 2024-01-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_sales_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unique_nums',
            field=models.CharField(max_length=250),
        ),
    ]
