# Generated by Django 4.2.6 on 2024-01-31 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="role",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="app1.role"
            ),
        ),
    ]
