# Generated by Django 4.2.7 on 2023-12-11 09:44

import assign7.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('user_name', models.CharField(max_length=100)),
                ('password', assign7.models.EncryptionField()),
            ],
        ),
    ]
