# Generated by Django 4.2.7 on 2023-12-11 10:03

import assign7.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign7', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=assign7.models.EncryptionField(),
        ),
    ]
