# Generated by Django 4.2.7 on 2023-12-07 07:08

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('cust_id', models.SmallIntegerField(default=0)),
                ('adhar', models.BigIntegerField(default=0)),
                ('value_less_zero', app.models.NegativeIntegerField(default=-1)),
                ('min_value_id', models.SmallIntegerField(default=23, validators=[django.core.validators.MinValueValidator(limit_value=23, message='value should greater than zero')])),
                ('phoneno', models.CharField(max_length=10)),
                ('data', app.models.EncryptionField()),
            ],
        ),
    ]
