# Generated by Django 4.2.7 on 2023-12-07 11:51

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='shravn', max_length=50, null=True, validators=[app.models.name_validator], verbose_name='Name')),
                ('phone', models.CharField(default=0, max_length=10, null=True, validators=[app.models.phone_validator], verbose_name='Phone Number')),
                ('email', models.EmailField(default='admin@gmail.com', max_length=25, null=True, verbose_name='Email')),
                ('address', models.TextField(default='3-5,Hyderabad', max_length=255, null=True, verbose_name='Address')),
                ('branch', models.CharField(default='EIE', max_length=25, null=True, verbose_name='Branch')),
                ('year', models.CharField(default='1st', max_length=20, null=True, verbose_name='Year')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image Upload')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
            ],
        ),
    ]
