# Generated by Django 4.2.7 on 2023-12-07 12:13

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default=0, max_length=15, null=True, validators=[app.models.phone_validator], verbose_name='Phone Number'),
        ),
    ]
