# Generated by Django 4.2.6 on 2023-12-29 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_name", models.CharField(max_length=250)),
                ("price", models.IntegerField()),
                ("descrpition", models.TextField()),
                ("location", models.CharField(max_length=250)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app1.customer"
                    ),
                ),
            ],
        ),
    ]
