# Generated by Django 4.2.6 on 2024-01-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_alter_product_purchase_orders_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="purchase_orders",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sales_orders",
        ),
        migrations.AddField(
            model_name="purchase",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="app1.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sales",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="app1.product",
            ),
            preserve_default=False,
        ),
    ]
