# Generated by Django 4.2.7 on 2024-02-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0002_tripmember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tripmember',
            new_name='trip',
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arms.trip')),
            ],
        ),
    ]
