# Generated by Django 4.2.7 on 2024-02-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0003_rename_tripmember_trip_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('reasons', models.CharField(max_length=250)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arms.trip')),
            ],
        ),
    ]
