# Generated by Django 4.2.7 on 2024-02-08 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0004_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='arms.role'),
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_get', models.BooleanField(default=False)),
                ('has_post', models.BooleanField(default=False)),
                ('has_put', models.BooleanField(default=False)),
                ('has_delete', models.BooleanField(default=False)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arms.api')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arms.role')),
            ],
        ),
    ]
