# Generated by Django 4.2.7 on 2024-02-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0005_api_alter_myuser_role_permissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Permission',
        ),
    ]
