# Generated by Django 4.2.7 on 2024-02-08 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0006_rename_permissions_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
