# version: "3"

# services:
#   app:
#     container_name: cont1
#     build:
#       context: .
#     command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py test && python manage.py runserver 0.0.0.0:8000"
#     ports:
#       - "8001:8000"  

#   nginx:
#     image: nginx
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       # - .C:\Users\pavan kumar\Desktop\fleet/nginx/nginx.conf:/etc/nginx/nginx.conf
#     ports:
#       - "80:80"
#     depends_on:
#       - app

  version: "3"

  services:
    app:
      container_name: cont1
      build:
        context: .
      command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py test && python manage.py runserver 0.0.0.0:8000"
      ports:
        - "8001:8000"  

    app2:
      container_name: cont11
      build:
        context: .
      command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py test && python manage.py runserver 0.0.0.0:8000"
      ports:
        - "8002:8000" 

    nginx:
      image: nginx
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        # - .C:\Users\pavan kumar\Desktop\fleet/nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:80"
      depends_on:
        - app
        - app2