version: "3"
 
services:
 
  app:
    container_name: iam
   
    build:
     context: .
    ports:
      - "8001:8000"
    command: >
        sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
   
    depends_on:
      - db
  db:
   
    container_name: trip
 
    image: mysql:latest
 
    environment:
      MYSQL_ROOT_PASSWORD : Lucky@143
      MYSQL_DATABASE : aja
 
    ports:
      - "3307:3306"
 
 
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginix/nginx.conf:/etc/nginx/nginx.conf  # Mount your Nginx configuration file
     
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - app