# Generated by Django 4.2.7 on 2023-12-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='name',
        ),
    ]
