# Generated by Django 4.2.7 on 2023-12-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_email_users_email_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email_id',
            new_name='email',
        ),
    ]
