# Generated by Django 4.2.3 on 2023-12-08 09:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', app.models.EencryptionField(max_length=20)),
                ('desi', models.CharField(max_length=40)),
            ],
        ),
    ]
