# Generated by Django 5.0 on 2024-02-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="created_by",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="updated_by",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="created_by",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="updated_by",
            field=models.IntegerField(blank=True),
        ),
    ]
