# Generated by Django 5.0 on 2024-02-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_trip_created_by_alter_trip_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="created_by",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="trip",
            name="updated_by",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="created_by",
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="updated_by",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
