# Generated by Django 5.0.1 on 2024-02-04 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="number",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="app.person"
            ),
        ),
    ]
