# Generated by Django 4.2.7 on 2024-01-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppos',
            old_name='purchacestock',
            new_name='purchasestock',
        ),
    ]
