# Generated by Django 4.2.7 on 2024-01-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_purchacestock_ppos_purchasestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingstock',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default="2024-01-11 05:59:35.435611"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ppos',
            name='purchasestock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ssos',
            name='salestock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(default='nill', max_length=25),
        ),
    ]
