# Generated by Django 4.2.7 on 2024-01-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_openingstock_created_date_alter_openingstock_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
