# Generated by Django 4.2.7 on 2023-12-16 12:53

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_id", models.EmailField(max_length=100)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=50)),
                ("validate_phone_number", models.SmallIntegerField()),
                (
                    "address",
                    models.CharField(
                        max_length=250,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                "invalid",
                            )
                        ],
                    ),
                ),
                ("tech_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Daily_Atendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "check_in",
                    models.TimeField(default=datetime.time(18, 23, 37, 100854)),
                ),
                ("check_out", models.TimeField()),
                ("status", models.CharField(max_length=1)),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelApp.employee",
                    ),
                ),
            ],
        ),
    ]
