# Generated by Django 4.2.7 on 2023-12-18 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_in",
            field=models.TimeField(default=datetime.time(9, 38, 44, 636953)),
        ),
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_out",
            field=models.TimeField(default=datetime.time(9, 38, 44, 636953)),
        ),
    ]
