# Generated by Django 4.2.7 on 2023-12-18 04:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0003_alter_daily_atendance_check_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_in",
            field=models.TimeField(default=datetime.time(10, 6, 44, 331484)),
        ),
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_out",
            field=models.TimeField(default=datetime.time(10, 6, 44, 331484)),
        ),
        migrations.AlterField(
            model_name="daily_atendance",
            name="employee_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="modelApp.employee"
            ),
        ),
    ]
