# Generated by Django 4.2.7 on 2023-12-18 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0004_alter_daily_atendance_check_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_in",
            field=models.TimeField(default=datetime.time(12, 48, 39, 188619)),
        ),
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_out",
            field=models.TimeField(default=datetime.time(12, 48, 39, 188619)),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email_id",
            field=models.EmailField(max_length=100),
        ),
    ]
