# Generated by Django 4.2.7 on 2023-12-18 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0007_alter_daily_atendance_check_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_in",
            field=models.TimeField(default=datetime.time(15, 46, 13, 302715)),
        ),
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_out",
            field=models.TimeField(default=datetime.time(15, 46, 13, 302715)),
        ),
    ]
