# Generated by Django 5.0 on 2023-12-20 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0011_alter_daily_atendance_check_in_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_in",
            field=models.TimeField(default=datetime.time(14, 48, 12, 800332)),
        ),
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_out",
            field=models.TimeField(default=datetime.time(14, 48, 12, 800332)),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email_id",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
