# Generated by Django 5.0 on 2023-12-20 11:50

import datetime
import django.db.models.deletion
import modelApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0012_alter_employee_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_in",
            field=models.TimeField(default=datetime.time(17, 20, 52, 63010)),
        ),
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_out",
            field=models.TimeField(default=datetime.time(17, 20, 52, 63010)),
        ),
        migrations.AlterField(
            model_name="daily_atendance",
            name="status",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(
                max_length=20, validators=[modelApp.models.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(
                max_length=50, validators=[modelApp.models.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="tech_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="modelApp.technology"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="validate_phone_number",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="technology",
            name="domain",
            field=models.CharField(
                max_length=50, validators=[modelApp.models.validate_name]
            ),
        ),
    ]
