# Generated by Django 5.0 on 2023-12-20 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0013_alter_daily_atendance_check_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_in",
            field=models.TimeField(default=datetime.time(17, 37, 21, 688259)),
        ),
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_out",
            field=models.TimeField(default=datetime.time(17, 37, 21, 688259)),
        ),
        migrations.AlterField(
            model_name="employee",
            name="tech_id",
            field=models.IntegerField(),
        ),
    ]
