# Generated by Django 5.0 on 2023-12-20 12:10

import datetime
import modelApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0014_alter_daily_atendance_check_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_in",
            field=models.TimeField(default=datetime.time(17, 40, 44, 508622)),
        ),
        migrations.AlterField(
            model_name="daily_atendance",
            name="check_out",
            field=models.TimeField(default=datetime.time(17, 40, 44, 508622)),
        ),
        migrations.AlterField(
            model_name="employee",
            name="validate_phone_number",
            field=models.IntegerField(
                unique=True, validators=[modelApp.models.validate_phno]
            ),
        ),
    ]
