data =  {"ambedkar": {"name": "Dr B.R. Ambedkar", "content": "Bhimrao Ramji Ambedkar was an Indian jurist, economist, social reformer, and political figure who served as the chairman of the committee that drafted the Constitution of India from the discussions in the Constituent Assembly", "img":"/static/app2/images/br.jpg"},
         "apj":{"name":" APJ Abdul Kalam", "content":"Scientist in aerospace and statesman Avul Pakir Jainulabdeen Abdul Kalam led India as its 11th president from 2002 to 2007", "img":"/static/app2/images/apj.jpg"},
         "gandhi":{"name":"Mahatma Gandhi", "content":"The victorious struggle for India’s independence from British control was led by Indian lawyer, anti-colonial nationalist, and political ethicist Mohandas Karamchand Gandhi, who later served as an inspiration for movements for civil rights and freedom around the globe.", "img":"/static/app2/images/gandhi.jpg"},
         "chari":{"name": "C. Rajagopalachari", "content":"Chakravarti Rajagopalachari was a statesman, author, lawyer, and champion for Indian independence. Rajagopalachari served as India’s final governor general before it became a republic in 1950.", "img":"/static/app2/images/chari.jpg"},
         "patal":{"name":"Sardar Vallabhai Patel", "content":"The first Deputy Prime Minister of India and the country’s first Home Minister, Vallabhbhai Jhaverbhai Patel, also known as Sardar, was an Indian lawyer, prominent political figure, lawyer, and statesman who served from 1947 to 1950.", "img":"/static/app2/images/patel.jpg"},
         "nehru":{"name":"Jawaharlal Nehru", "content":"A major personality in India throughout the middle of the 20th century, Jawaharlal Nehru was an anti-colonial patriot, secular humanist, social democrat, and author.", "img":"/static/app2/images/nehru.jpg"},
         "teresa":{"name":"Mother Teresa", "content":"Mother Teresa, commonly referred to as Saint Teresa of Calcutta, and a foremost name among the great leaders of India, was an Albanian-Indian Roman Catholic nun who founded the Missionaries of Charity in 1950 and was a prominent member of the order", "img":"/static/app2/images/teresa.jpg"},
         "atal":{"name":"Atal Bihari Vajpayee", "content":"As India’s 10th prime minister, Atal Bihari Vajpayee was an Indian politician and diplomat who held office for three terms: for 13 days in 1996, for 13 months from 1998 to 1999, and then for a full term from 1999 to 2004.", "img":"/static/app2/images/atal.jpg"},
         "baba":{"name":" Baba Amte", "content":"Indian social worker and activist Murlidhar Devidas Amte, better known by his stage name Baba Amte, is well renowned for his work in the rehabilitation and empowerment of leprosy patients.", "img":"/static/app2/images/baba.jpg"}
         
         }