# Generated by Django 4.2.7 on 2024-02-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_alter_city_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyStudentModel',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.student',),
        ),
    ]
