# Generated by Django 4.1 on 2023-12-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='aja@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
