# Generated by Django 4.1 on 2023-12-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhar',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='cust_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
