# Generated by Django 4.1 on 2023-12-07 09:26

import application.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_employee_aadhar_employee_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='value_less_zero',
            field=application.models.NegativeIntegerField(default=0),
        ),
    ]
