# Generated by Django 4.1 on 2023-12-07 09:29

import application.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_employee_value_less_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='value_less_zero',
            field=application.models.NegativeIntegerField(default=-1),
        ),
    ]
