# Generated by Django 4.1 on 2023-12-07 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_employee_value_less_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='min_value_id',
            field=models.SmallIntegerField(default=23, validators=[django.core.validators.MinValueValidator(limit_value=23, message='value should greater than zero')]),
        ),
    ]
