# Generated by Django 4.2.4 on 2023-12-21 08:50

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketer',
            name='image_path',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='cricketer',
            name='name',
            field=models.CharField(max_length=250, validators=[app1.models.only_alp], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cricketer',
            name='video',
            field=models.FileField(upload_to='', verbose_name='Video'),
        ),
    ]
