# Generated by Django 4.2.4 on 2023-12-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_cricketer_image_path_alter_cricketer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketer',
            name='video',
            field=models.FileField(null=True, upload_to='', verbose_name='Video'),
        ),
    ]
