# Generated by Django 4.2.4 on 2023-12-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_cricketer_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketer',
            name='image_path',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='cricketer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Video'),
        ),
    ]
