# Generated by Django 4.2.7 on 2023-12-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.CharField(default=236526, max_length=250),
            preserve_default=False,
        ),
    ]
