# Generated by Django 4.2.7 on 2023-12-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0002_employee_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email_id",
            field=models.CharField(max_length=250),
        ),
    ]
