# Generated by Django 4.2.7 on 2023-12-08 06:57

from django.db import migrations, models
import modelApp.models


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0004_employee_tech_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="employee",
            name="validate_phone_number",
            field=models.SmallIntegerField(
                default=7687567678, validators=[modelApp.models.validate_phoneNum]
            ),
            preserve_default=False,
        ),
    ]
