# Generated by Django 4.2.7 on 2023-12-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0013_alter_employee_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=20),
        ),
    ]
