# Generated by Django 4.2.7 on 2023-12-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0014_alter_employee_first_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tech_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trainer_name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "tech",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelApp.technology",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="tech_emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelApp.employee",
                    ),
                ),
                (
                    "tech",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelApp.technology",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="daily_Atendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=1)),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelApp.employee",
                    ),
                ),
            ],
        ),
    ]
