# Generated by Django 4.2.7 on 2023-12-16 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("modelApp", "0002_technology_remove_employee_phone_number_and_more"),
        ("modelApp", "0015_technology_trainer_tech_emp_daily_atendance"),
    ]

    operations = []
