# Generated by Django 4.2.7 on 2023-12-10 07:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email_id', models.EmailField(max_length=250)),
                ('phone_no', models.BigIntegerField()),
                ('graduation', models.CharField(max_length=100)),
                ('graduation_stream', models.CharField(max_length=150)),
                ('graduation_year', models.SmallIntegerField()),
                ('post_graduation', models.CharField(max_length=100)),
                ('post_graduation_stream', models.CharField(max_length=150)),
                ('post_graduation_year', models.SmallIntegerField(default=0)),
                ('trained_on_technology', models.CharField(max_length=250)),
                ('institute_name', models.TextField(max_length=500)),
                ('course_duration', models.CharField(max_length=100)),
                ('reference_name', models.CharField(max_length=250)),
                ('experience', models.BooleanField(default=False)),
                ('experience_years', models.SmallIntegerField(default=0)),
                ('previous_company_name', models.TextField(max_length=500)),
                ('current_ctc', models.BigIntegerField(default=0)),
                ('expected_ctc', models.BigIntegerField(default=0)),
                ('pf', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 12, 10, 13, 2, 59, 931199))),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_marks', models.FloatField()),
                ('online_status', models.BooleanField(default=False)),
                ('online_feedback', models.TextField()),
                ('comm_marks', models.FloatField()),
                ('comm_status', models.BooleanField(default=False)),
                ('comm_feedback', models.TextField()),
                ('tech_marks', models.FloatField()),
                ('tech_status', models.BooleanField(default=False)),
                ('tech_feedback', models.TextField()),
                ('is_selected', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task9app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Joined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_joined', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task9app.users')),
            ],
        ),
    ]
