# Generated by Django 4.2.7 on 2023-12-10 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task9app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 13, 3, 42, 751451)),
        ),
    ]
