# Generated by Django 4.2.7 on 2023-12-10 11:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task9app', '0003_alter_users_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 16, 40, 25, 672120)),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_no',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1000000000), django.core.validators.MaxValueValidator(limit_value=9999999999)]),
        ),
    ]
