# Generated by Django 4.2.7 on 2023-12-10 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task9app', '0004_alter_users_created_at_alter_users_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 17, 5, 26, 473589)),
        ),
    ]
