# Generated by Django 4.2.7 on 2023-12-11 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task9app', '0007_alter_users_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 15, 14, 3, 845760)),
        ),
    ]
