# Generated by Django 5.0.1 on 2024-02-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="start_date",
            field=models.DateField(),
        ),
    ]
