# Generated by Django 5.0 on 2023-12-19 09:25

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "total_price",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("price"),
                            "-",
                            django.db.models.expressions.CombinedExpression(
                                models.F("discount"), "/", models.Value(100)
                            ),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=10
                        ),
                    ),
                ),
            ],
        ),
    ]
