# Generated by Django 5.0 on 2023-12-19 09:30

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testApp1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="total_price",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.expressions.CombinedExpression(
                        models.F("discount"), "/", models.F("price")
                    ),
                    "*",
                    models.Value(100),
                ),
                output_field=models.DecimalField(decimal_places=2, max_digits=10),
            ),
        ),
    ]
