# Generated by Django 4.2.7 on 2024-02-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='product',
            new_name='product_id',
        ),
    ]
