# Generated by Django 4.2.7 on 2024-02-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_product_purchaseorder_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
