# Generated by Django 5.0 on 2024-01-05 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_unque_number", models.CharField(max_length=250, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="serapp.category",
                    ),
                ),
                (
                    "purchase_orders",
                    models.ManyToManyField(blank=True, to="serapp.purchaseorder"),
                ),
                (
                    "sales_orders",
                    models.ManyToManyField(blank=True, to="serapp.salesorder"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpeningStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "prodcut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="serapp.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "prodcut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="serapp.product"
                    ),
                ),
            ],
        ),
    ]
