# Generated by Django 5.0 on 2024-01-05 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("serapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productcost",
            old_name="prodcut",
            new_name="product",
        ),
    ]
