# Generated by Django 5.0 on 2024-01-05 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("erpApp", "0002_alter_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="openingstock",
            old_name="prodcut",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="productcost",
            old_name="prodcut",
            new_name="product",
        ),
    ]
