# Generated by Django 5.0 on 2024-01-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erpApp", "0003_rename_prodcut_openingstock_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="purchase_orders",
            field=models.ManyToManyField(blank=True, to="erpApp.purchaseorder"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sales_orders",
            field=models.ManyToManyField(blank=True, to="erpApp.salesorder"),
        ),
    ]
