# Generated by Django 5.0 on 2024-01-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erpApp", "0006_alter_stock_refid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productsales",
            old_name="purchase",
            new_name="sales",
        ),
        migrations.AddField(
            model_name="product",
            name="purchase_orders",
            field=models.ManyToManyField(blank=True, to="erpApp.purchaseorder"),
        ),
        migrations.AddField(
            model_name="product",
            name="sales_orders",
            field=models.ManyToManyField(blank=True, to="erpApp.salesorder"),
        ),
        migrations.AlterField(
            model_name="productpurchase",
            name="stock",
            field=models.PositiveIntegerField(),
        ),
    ]
