# Generated by Django 5.0 on 2024-01-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erpApp", "0007_rename_purchase_productsales_sales_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=30000.0, max_digits=10),
            preserve_default=False,
        ),
    ]
