# Generated by Django 5.0 on 2024-01-25 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erpApp", "0008_product_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productpurchase",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productpurchase",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="productsales",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productsales",
            name="sales",
        ),
        migrations.RemoveField(
            model_name="product",
            name="purchase_orders",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sales_orders",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="product",
        ),
        migrations.RemoveField(
            model_name="openingstock",
            name="created",
        ),
        migrations.RemoveField(
            model_name="openingstock",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_unque_number",
        ),
        migrations.AddField(
            model_name="openingstock",
            name="opening_stock",
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="product_unque_num",
            field=models.CharField(default="yr56", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField()),
                ("description", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="erpApp.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField()),
                ("description", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="erpApp.product"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProductCost",
        ),
        migrations.DeleteModel(
            name="ProductPurchase",
        ),
        migrations.DeleteModel(
            name="ProductSales",
        ),
        migrations.DeleteModel(
            name="PurchaseOrder",
        ),
        migrations.DeleteModel(
            name="SalesOrder",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
