# Generated by Django 5.0.1 on 2024-02-04 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.IntegerField(null=True)),
                ("update_by", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("type_of_vehicle", models.CharField(max_length=20)),
                ("no_of_seats", models.IntegerField()),
                ("vehicle_no", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.IntegerField(null=True)),
                ("update_by", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("no_of_people", models.IntegerField()),
                (
                    "vehicles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.vehicle"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
