# Generated by Django 4.2.4 on 2023-12-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aspirants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email_id', models.EmailField(max_length=250)),
                ('phone_no', models.BigIntegerField()),
                ('gradution', models.CharField(max_length=100)),
                ('post_gradution', models.CharField(max_length=100, null=True)),
                ('stream', models.CharField(max_length=100, null=True)),
                ('passed_out_year', models.SmallIntegerField(null=True)),
                ('trained_on_technology', models.CharField(max_length=100, null=True)),
                ('institue_name', models.CharField(max_length=300, null=True)),
                ('duration_of_course', models.SmallIntegerField(null=True)),
                ('Reference_name', models.CharField(max_length=250, null=True)),
                ('experience', models.SmallIntegerField(null=True)),
                ('previous_company_name', models.CharField(max_length=250, null=True)),
                ('current_ctc', models.BigIntegerField(null=True)),
                ('expected_ctc', models.BigIntegerField(null=True)),
            ],
        ),
    ]
