# Generated by Django 4.2.4 on 2023-12-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rigportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_onlinetest', models.SmallIntegerField()),
                ('isqualified_onlinetest', models.BooleanField(default=True)),
                ('feedback_online', models.CharField(max_length=250)),
                ('marks_communicationtest', models.SmallIntegerField()),
                ('isqualified_communicationtest', models.BooleanField(default=True)),
                ('feedback_communication', models.CharField(max_length=250)),
                ('marks_technicaltest', models.SmallIntegerField()),
                ('isqualified_technical', models.BooleanField(default=True)),
                ('feedback_technical', models.CharField(max_length=250)),
                ('is_selected', models.BooleanField(default=True)),
                ('feedback', models.CharField(max_length=250)),
                ('aspirantsid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rigportal.aspirants')),
            ],
        ),
        migrations.CreateModel(
            name='onboared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_onboared', models.BooleanField(default=True)),
                ('aspirantsid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rigportal.aspirants')),
            ],
        ),
    ]
