# Generated by Django 4.2.7 on 2024-01-24 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app1", "0007_address_country_region_person_created_by_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="created_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="update",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="updated_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="create",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
