# Generated by Django 4.2.7 on 2024-01-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0008_person_created_date_person_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
