# Generated by Django 4.2.7 on 2024-01-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0009_alter_person_created_date_alter_person_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="updated_date",
            field=models.DateTimeField(null=True),
        ),
    ]
