# Generated by Django 4.2.7 on 2024-01-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0010_alter_person_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="updated_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
