# Generated by Django 4.2.7 on 2024-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0011_alter_person_updated_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
