# Generated by Django 4.2.7 on 2024-01-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0012_person_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
