# Generated by Django 4.2.7 on 2024-01-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='a',
            field=models.IntegerField(null=True),
        ),
    ]
