# Generated by Django 4.2.7 on 2024-01-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arms', '0002_myuser_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='a',
        ),
    ]
