# Generated by Django 4.2.7 on 2023-12-21 06:28

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True, validators=[app.models.fullname], verbose_name='Full Name')),
                ('email', models.EmailField(max_length=50, null=True, validators=[app.models.emailid], verbose_name='Email_ID')),
                ('phone_no', models.CharField(max_length=13, null=True, validators=[app.models.moblie], verbose_name='Phone Number')),
                ('gradution', models.CharField(choices=[('B.Tech', 'B.Tech'), ('Bcom', 'Bcom'), ('M.Tech', 'M.Tech'), ('BE', 'BE'), ('BCA', 'BCA'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('MSc', 'MSc'), ('MA', 'MA'), ('B Sc', 'B Sc')], max_length=50, null=True, validators=[app.models.gradutionyear], verbose_name='Gradution')),
                ('post_gradution', models.CharField(max_length=50, null=True, verbose_name='Post Gradution')),
                ('stream', models.CharField(max_length=50, null=True, verbose_name='Stream')),
                ('passed_out_year', models.IntegerField(null=True, verbose_name='Passed out year')),
                ('trained_on_technology', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('DotNet', 'DotNet'), ('Devops', 'Devops'), ('Testing', 'Testing'), ('Salesforce', 'Salesforce'), ('ReactJS', 'ReactJS'), ('DataScience', 'DataScience')], max_length=50, null=True, verbose_name='Trained on Technology')),
                ('trained_institue', models.CharField(max_length=50, null=True, verbose_name='Where did you trained institue name')),
                ('duration_of_course', models.CharField(max_length=50, null=True, verbose_name='Duration of course')),
                ('reference_name', models.CharField(max_length=25, null=True, verbose_name='Refernce Name')),
                ('hear_about_interview', models.CharField(max_length=50, null=True, verbose_name='Where did you hear about the interview')),
                ('experience', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=25, null=True, verbose_name='Experience')),
                ('Previous_company_name', models.CharField(max_length=50, null=True, verbose_name='Previous Company Name')),
                ('current_ctc', models.CharField(max_length=50, null=True, verbose_name='Current_CTC')),
                ('expected_ctc', models.CharField(max_length=50, null=True, verbose_name='Expected_CTC')),
                ('last_company', models.CharField(max_length=50, null=True, verbose_name='Do you have PF in last company')),
                ('years_of_experience', models.CharField(max_length=50, null=True, verbose_name='How many year of experice')),
                ('created_at', models.DateField(null=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_onlinetest', models.FloatField(max_length=25, null=True)),
                ('isQualified_online', models.BooleanField(default=False)),
                ('feedback_online', models.TextField(max_length=58)),
                ('marks_communication_test', models.FloatField(max_length=25)),
                ('isQualified_comm', models.BooleanField(default=False)),
                ('feedback_comm', models.TextField(max_length=52)),
                ('marks_technicaltest', models.FloatField(max_length=22)),
                ('isQualified_test', models.BooleanField(default=False)),
                ('feedback_technical', models.TextField(max_length=52)),
                ('isselected', models.BooleanField(default=False)),
                ('feedback', models.TextField(max_length=250)),
                ('aspirantsid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.aspirant')),
            ],
        ),
        migrations.CreateModel(
            name='Onboared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Onboarded', models.BooleanField(default=False)),
                ('Aspirantid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.aspirant')),
            ],
        ),
    ]
