# Generated by Django 4.2.7 on 2023-12-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradution', models.CharField(max_length=50, null=True, verbose_name='Gradution')),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_onlinetest', models.FloatField(max_length=25, null=True)),
                ('isQualified_online', models.BooleanField(default=False)),
                ('feedback_online', models.TextField(max_length=58)),
                ('marks_communication_test', models.FloatField(max_length=25)),
                ('isQualified_comm', models.BooleanField(default=False)),
                ('feedback_comm', models.TextField(max_length=52)),
                ('marks_technicaltest', models.FloatField(max_length=22)),
                ('isQualified_test', models.BooleanField(default=False)),
                ('feedback_technical', models.TextField(max_length=52)),
                ('isselected', models.BooleanField(default=False)),
                ('feedback', models.TextField(max_length=250)),
                ('aspirantsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aspirant')),
            ],
        ),
        migrations.CreateModel(
            name='Onboared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Onboarded', models.BooleanField(default=False)),
                ('Aspirantid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aspirant')),
            ],
        ),
    ]
