# Generated by Django 4.2.7 on 2023-12-21 06:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='gradution',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('Bcom', 'Bcom'), ('M.Tech', 'M.Tech'), ('BE', 'BE'), ('BCA', 'BCA'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('MSc', 'MSc'), ('MA', 'MA'), ('B Sc', 'B Sc')], max_length=50, null=True, verbose_name='Gradution'),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='passed_out_year',
            field=models.IntegerField(null=True, validators=[app.models.gradutionyear], verbose_name='Passed out year'),
        ),
    ]
