# Generated by Django 4.2.7 on 2023-12-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_aspirant_gradution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
    ]
