# Generated by Django 4.2.7 on 2023-12-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aspirant_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirant',
            name='Previous_company_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Previous Company Name'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='application_no',
            field=models.IntegerField(max_length=255, null=True, verbose_name='Appliation_Number'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='created_at',
            field=models.DateField(null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='current_ctc',
            field=models.CharField(max_length=50, null=True, verbose_name='Current_CTC'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='duration_of_course',
            field=models.CharField(max_length=50, null=True, verbose_name='Duration of course'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Email_ID'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='expected_ctc',
            field=models.CharField(max_length=50, null=True, verbose_name='Expected_CTC'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='experience',
            field=models.CharField(max_length=25, null=True, verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='full_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='hear_about_interview',
            field=models.CharField(max_length=50, null=True, verbose_name='Where did you hear about the interview'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='last_company',
            field=models.CharField(max_length=50, null=True, verbose_name='Do you have PF in last company'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='passed_out_year',
            field=models.IntegerField(max_length=4, null=True, verbose_name='Passed out year'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='post_gradution',
            field=models.CharField(max_length=50, null=True, verbose_name='Post Gradution'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='reference_name',
            field=models.CharField(max_length=25, null=True, verbose_name='Refernce Name'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='stream',
            field=models.CharField(max_length=50, null=True, verbose_name='Stream'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='trained_institue',
            field=models.CharField(max_length=50, null=True, verbose_name='Where did you trained institue name'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='trained_on_technology',
            field=models.CharField(max_length=50, null=True, verbose_name='Trained on Technology'),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='years_of_experience',
            field=models.CharField(max_length=50, null=True, verbose_name='How many year of experice'),
        ),
    ]
