# Generated by Django 4.2.7 on 2023-12-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aspirant_previous_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='application_no',
            field=models.IntegerField(null=True, verbose_name='Appliation_Number'),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='passed_out_year',
            field=models.IntegerField(null=True, verbose_name='Passed out year'),
        ),
    ]
