# Generated by Django 4.2.7 on 2023-12-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_aspirant_application_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboared',
            name='Aspirantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.aspirant'),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='aspirantsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.aspirant'),
        ),
    ]
