# Generated by Django 4.2.7 on 2023-12-16 11:56

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_onboared_aspirantid_alter_rounds_aspirantsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirant',
            name='application_no',
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='created_at',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
