# Generated by Django 4.2.7 on 2023-12-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_aspirant_application_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='created_at',
            field=models.DateField(null=True, verbose_name='Created at'),
        ),
    ]
