# Generated by Django 4.2.4 on 2023-12-28 09:08

import app1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.BigIntegerField(default=app1.models.get_next_application_no)),
                ('first_name', models.CharField(max_length=100, validators=[app1.models.only_alp], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, validators=[app1.models.only_alp], verbose_name='Last Name')),
                ('email_ID', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone_No', models.BigIntegerField(verbose_name='Phone Number')),
                ('graduation', models.CharField(max_length=100, verbose_name='Graduation')),
                ('stream', models.CharField(max_length=10, verbose_name='Stream')),
                ('grad_yop', models.IntegerField(verbose_name='Graduation year of pass')),
                ('post_graduation', models.CharField(max_length=100, verbose_name='Post Graduation')),
                ('pg_Stream', models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Graduation Stream')),
                ('pg_Passed_Out_Year', models.IntegerField(blank=True, null=True, verbose_name='Post Graduation Year of Pass')),
                ('trained_On_Technology', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('DotNet', 'DotNET'), ('Salesforce', 'Salesforce'), ('ReactJS', 'ReactJS'), ('DevOps', 'DevOps')], max_length=100, verbose_name='Technology Trained On')),
                ('institute_Name', models.CharField(max_length=250, validators=[app1.models.only_alp], verbose_name='Name of the Institute where you Trained')),
                ('duration_of_course', models.IntegerField(verbose_name='Course Duration')),
                ('reference_Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Name')),
                ('hear_about_the_interview', models.CharField(max_length=250, validators=[app1.models.only_alp], verbose_name='Where did you heard about the interview?')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Experience')),
                ('previous_company_Name', models.CharField(max_length=250, validators=[app1.models.only_alp], verbose_name='Name of Previous Company Name')),
                ('current_CTC', models.IntegerField(blank=True, null=True, verbose_name='Current CTC')),
                ('expected_CTC', models.IntegerField(blank=True, null=True, verbose_name='Expect CTC')),
                ('pf_in_Last_Company', models.BooleanField(blank=True, null=True, verbose_name='Do you have PF')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_communication_test', models.IntegerField(verbose_name='Marks')),
                ('isQualified_communication_test', models.BooleanField(verbose_name='Qualified or Not Qualified')),
                ('feedback_communication_test', models.TextField(verbose_name='Feedback')),
                ('marks_technical_test', models.IntegerField(null=True, verbose_name='Marks')),
                ('isQualified_technical_test', models.BooleanField(null=True, verbose_name='Qualified or Not Qualified')),
                ('feedback_technical_test', models.TextField(null=True, verbose_name='Marks')),
                ('aspirantid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.aspirant')),
            ],
        ),
        migrations.CreateModel(
            name='OnBoarded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isonboared', models.BooleanField()),
                ('aspirantid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.aspirant')),
            ],
        ),
    ]
