# Generated by Django 4.2.4 on 2023-12-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='feedback_CEO_test',
            field=models.TextField(null=True, verbose_name='Marks'),
        ),
        migrations.AddField(
            model_name='rounds',
            name='isQualified_CEO_test',
            field=models.BooleanField(null=True, verbose_name='Selected or Not Selected'),
        ),
        migrations.AddField(
            model_name='rounds',
            name='marks_CEO_test',
            field=models.IntegerField(null=True, verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='onboarded',
            name='isonboared',
            field=models.BooleanField(verbose_name='On Boarded or Not On Boarded'),
        ),
    ]
