# Generated by Django 4.2.4 on 2023-12-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rounds_feedback_ceo_test_rounds_isqualified_ceo_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarded',
            name='isonboared',
            field=models.BooleanField(null=True, verbose_name='On Boarded or Not On Boarded'),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='isQualified_communication_test',
            field=models.BooleanField(null=True, verbose_name='Qualified or Not Qualified'),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='marks_communication_test',
            field=models.IntegerField(null=True, verbose_name='Marks'),
        ),
    ]
