# Generated by Django 4.2.4 on 2023-12-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_onboarded_isonboared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='isQualified_CEO_test',
            field=models.BooleanField(null=True, verbose_name='Selected '),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='isQualified_communication_test',
            field=models.BooleanField(null=True, verbose_name='Qualified'),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='isQualified_technical_test',
            field=models.BooleanField(null=True, verbose_name='Qualified'),
        ),
    ]
