# Generated by Django 4.2.4 on 2023-12-28 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_rounds_isqualified_ceo_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='marks_CEO_test',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=10)], verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='marks_communication_test',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=10)], verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='marks_technical_test',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=10)], verbose_name='Marks'),
        ),
    ]
