# Generated by Django 4.2.7 on 2023-12-16 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_alter_users_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 18, 45, 59, 121014)),
        ),
        migrations.AlterField(
            model_name='users',
            name='experience',
            field=models.CharField(max_length=250),
        ),
    ]
