# Generated by Django 4.2.7 on 2023-12-17 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_alter_users_created_at_alter_users_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 16, 35, 41, 253631)),
        ),
    ]
