# Generated by Django 4.2.7 on 2023-12-29 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=25, null=True)),
                ('dept_location', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('job_name', models.CharField(max_length=25, null=True)),
                ('salary', models.FloatField(null=True)),
                ('hire_date', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.department')),
            ],
        ),
    ]
