# Generated by Django 5.0 on 2023-12-20 06:58

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Square",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("side", models.IntegerField()),
                (
                    "area",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("side"), "*", models.F("side")
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
            ],
        ),
    ]
