# Generated by Django 4.2.6 on 2024-01-05 09:28

from django.db import migrations, models
import django.db.models.deletion
import serApp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, validators=[serApp.models.name_check]
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, validators=[serApp.models.email_check]
                    ),
                ),
                ("phone", models.IntegerField(validators=[serApp.models.phone_check])),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        max_length=250, validators=[serApp.models.name_check]
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="serApp.employee",
                    ),
                ),
            ],
        ),
    ]
