# Generated by Django 4.2.6 on 2024-01-05 10:41

from django.db import migrations, models
import serApp.models


class Migration(migrations.Migration):
    dependencies = [
        ("serApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(
                max_length=250, unique=True, validators=[serApp.models.name_check]
            ),
        ),
    ]
