# Generated by Django 4.2.6 on 2023-12-21 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MediaApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Media",
            new_name="MediaDB",
        ),
    ]
