# Generated by Django 4.2.3 on 2023-12-16 06:50

import arm.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_join', models.DateField(default=datetime.date(2023, 12, 16))),
                ('technology_cat', models.CharField(choices=[('python', 'python'), ('java', 'java'), ('Reactjs', 'Reactjs'), ('.NET', '.NET'), ('Salesforce', 'Salesforce'), ('Devops', 'Devops')], max_length=100)),
                ('designation', models.CharField(choices=[('HR', 'HR'), ('Trainee software', 'Trainee software'), ('Finance manger', 'Finance manger'), ('Software engineer', 'Software engineer'), ('principil consultant', 'principil consultant'), ('manager', 'manager')], max_length=250)),
                ('employee_status', models.CharField(choices=[('under training', 'under training'), ('training completed', 'training completed'), ('Deployed', 'Deployed'), ('On bench', 'On bench')], max_length=300)),
                ('graduation', models.CharField(choices=[('Bsc', 'Bsc'), ('Btech', 'Btech'), ('AgBSc', 'AgBSc'), ('BBA', 'BBA'), ('Bcom', 'Bcom'), ('BE', 'BE'), ('BCA', 'BCA')], max_length=300)),
                ('stream', models.CharField(choices=[('computer science', 'computer science'), ('mathematics', 'mathematics'), ('science', 'science'), ('data science', 'data science'), ('computer applications', 'computer applications')], max_length=250)),
                ('ug_year_of_passout', models.DateField()),
                ('pg_education', models.CharField(choices=[('Msc', 'Msc'), ('MBA', 'MBA'), ('Mtech', 'Mtech'), ('ME', 'ME'), ('MCA', 'MCA')], max_length=250)),
                ('pg_education_passout_year', models.DateField()),
                ('pg_stram', models.CharField(choices=[('computer science', 'computer science'), ('mathematics', 'mathematics'), ('science', 'science'), ('data science', 'data science'), ('computer applications', 'computer applications'), ('civil engineering', 'civil engineering'), ('Finance', 'Finance'), ('IT', 'IT')], max_length=250)),
                ('mobile_no', models.IntegerField(validators=[arm.models.phon_num])),
                ('alt_mobile_no', models.IntegerField(validators=[arm.models.phon_num])),
                ('remarks', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pricipal_consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consultant_name', models.CharField(max_length=50)),
                ('clients', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arm.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_exit', models.DateTimeField()),
                ('exit_reason', models.CharField(max_length=250)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arm.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Deployed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_deploy', models.DateField(default=datetime.date(2023, 12, 16))),
                ('designation', models.CharField(max_length=150)),
                ('resource_type', models.CharField(choices=[('contract based', 'contract based'), ('full time', 'full time'), ('off shore', 'off shore')], max_length=250)),
                ('client', models.CharField(max_length=150)),
                ('project_start_date', models.DateField(default=datetime.date(2023, 12, 16), verbose_name=' Enter project start date')),
                ('project_end_date', models.DateField(verbose_name='Enter project end date')),
                ('billstatus', models.BooleanField(choices=[('paid', True), ('unpaid', False)])),
                ('bill_rate_per_month', models.IntegerField()),
                ('candidate_ctc', models.IntegerField()),
                ('work_mode', models.CharField(choices=[('Hybrid Mode', 'Hybrid mode'), ('WTH', 'WTH'), ('WFO', 'WFO')], max_length=200)),
                ('work_location', models.CharField(choices=[('Hyderabad', 'hyderabad'), ('Bangolore', 'Bangolore'), ('chennai', 'chennai'), ('Mumbai', 'Mumbai'), ('Kochi', 'Kochi'), ('Delhi', 'Delhi'), ('Pune', 'Pune'), ('Kolkata', 'Kolkata'), ('Coimbatore', 'Coimbatore'), ('other', 'other')], max_length=200)),
                ('remarks', models.TextField(max_length=300)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arm.employee')),
                ('principil_consultent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arm.pricipal_consultant')),
            ],
        ),
    ]
