# Generated by Django 5.0 on 2024-01-06 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manytomany", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="inviter",
        ),
    ]
