# Generated by Django 4.2.6 on 2023-12-08 09:51

import FieldApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("username", models.CharField(max_length=100)),
                ("password", FieldApp.models.EncryptionField()),
                ("email", models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
