# Generated by Django 4.2.6 on 2023-12-08 03:19

import base.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerbase",
            name="name_upper",
            field=base.models.UpperCaseField(default="", max_length=250),
        ),
    ]
