# Generated by Django 4.2.6 on 2023-12-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_customerbase_name_upper"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerbase",
            name="name_upper",
        ),
        migrations.RemoveField(
            model_name="customerbase",
            name="value_less_zero",
        ),
        migrations.AddField(
            model_name="customerbase",
            name="address",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AddField(
            model_name="customerbase",
            name="email",
            field=models.EmailField(default="", max_length=100),
        ),
    ]
