# Generated by Django 4.2.6 on 2023-12-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_cricketers_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cricketers",
            name="image_path",
            field=models.ImageField(max_length=250, upload_to=""),
        ),
    ]
