# Generated by Django 5.0 on 2023-12-21 09:33

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='name',
            field=models.CharField(max_length=50, validators=[application.models.special_symbols]),
        ),
    ]
