# Generated by Django 5.0 on 2023-12-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='display',
            name='mobile_number',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
