# Generated by Django 5.0 on 2023-12-18 09:38

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('costprice', models.FloatField()),
                ('profit', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('sellingprice', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('costprice'), '+', models.F('profit')), '+', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('discount'), '/', models.Value(100)), '*', models.F('costprice'))), output_field=models.FloatField())),
            ],
        ),
    ]
