# Generated by Django 4.2.4 on 2023-12-07 11:37

from django.db import migrations, models
import sample.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('email', sample.models.EncryptionField(default='', max_length=100)),
                ('cust_id', models.SmallIntegerField(default=0)),
                ('adhar', models.BigIntegerField(default=0)),
                ('value_less_zero', models.SmallIntegerField(default=-1)),
            ],
        ),
    ]
