# Generated by Django 4.2.4 on 2023-12-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='value_less_zero',
        ),
    ]
