# Generated by Django 4.2.6 on 2023-12-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(default="sample@gmail.com", max_length=100),
            preserve_default=False,
        ),
    ]
