# Generated by Django 4.2.6 on 2023-12-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0002_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="adhar",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="cust_id",
            field=models.SmallIntegerField(default=0),
        ),
    ]
