# Generated by Django 4.2.6 on 2023-12-07 03:13

from django.db import migrations
import sample.models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0003_customer_adhar_customer_cust_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="value_less_zero",
            field=sample.models.NegativeIntegerField(default=-1),
        ),
    ]
