# Generated by Django 4.2.6 on 2023-12-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0005_customer_min_value_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
    ]
