# Generated by Django 4.2.6 on 2023-12-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0006_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
    ]
