# Generated by Django 4.2.6 on 2023-12-08 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0007_person1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="adhar",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="cust_id",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="min_value_id",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="value_less_zero",
        ),
    ]
