# Generated by Django 4.2.7 on 2024-01-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
