# Generated by Django 4.2.7 on 2023-12-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='first_name',
            field=models.CharField(default='nithisha', max_length=10),
            preserve_default=False,
        ),
    ]
