# Generated by Django 5.0 on 2024-01-09 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openingstock",
            name="description",
        ),
    ]
