# Generated by Django 5.0 on 2023-12-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='Experience',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='Graduation_Passed_Out_Year',
            field=models.IntegerField(help_text='passed out year should be >2016 and <2023', null=True),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='Post_Gradation_Passed_out_year',
            field=models.IntegerField(null=True),
        ),
    ]
