# Generated by Django 5.0 on 2023-12-29 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Roll_number", models.CharField(max_length=100)),
                ("Branch", models.CharField(max_length=50)),
                (
                    "Student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app1.person"
                    ),
                ),
            ],
        ),
    ]
