# Generated by Django 5.0 on 2023-12-29 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="Student_id",
            new_name="person_id",
        ),
    ]
