# Generated by Django 5.0 on 2023-12-29 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_rename_student_id_student_person_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="Branch",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="Roll_number",
            new_name="roll_number",
        ),
    ]
