# Generated by Django 4.2.3 on 2024-01-06 10:44

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uniquenumber', models.IntegerField(unique=True)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('created', models.DateField(validators=[app.models.validate_date_not_in_future])),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('created', models.DateField(validators=[app.models.validate_date_not_in_future])),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('refid', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
                ('salesorderid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
                ('purchaseorderid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(validators=[app.models.validate_date_not_in_future])),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_orders',
            field=models.ManyToManyField(to='app.purchaseorder'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_orders',
            field=models.ManyToManyField(to='app.salesorder'),
        ),
        migrations.CreateModel(
            name='OpeningStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('date', models.DateField(validators=[app.models.validate_date_not_in_future])),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product')),
            ],
        ),
    ]
