# Generated by Django 4.2.7 on 2023-12-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateField(),
        ),
    ]
