# Generated by Django 4.2.7 on 2023-12-18 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0002_alter_employee_date_of_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 12, 18, 16, 58, 19, 266198)),
        ),
    ]
