# Generated by Django 4.2.7 on 2023-12-19 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0004_alter_employee_date_of_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('date', models.DateField()),
                ('login_time', models.TimeField()),
                ('logout_time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_join',
            field=models.DateField(default=datetime.date(2023, 12, 19)),
        ),
    ]
