# Generated by Django 4.2.7 on 2023-12-20 12:36

import attend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0007_rename_employee_employeeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='employee_id',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='first_name',
            field=models.CharField(max_length=50, validators=[attend_app.models.alpha]),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='last_name',
            field=models.CharField(max_length=50, validators=[attend_app.models.alpha]),
        ),
    ]
