# Generated by Django 4.2.7 on 2023-12-21 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0008_alter_employeeinfo_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='date_of_join',
            field=models.DateField(default=datetime.date(2023, 12, 21)),
        ),
    ]
