# Generated by Django 4.2.7 on 2023-12-22 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend_app', '0010_remove_employeeinfo_image_employeeinfo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='date_of_join',
            field=models.DateField(default=datetime.date(2023, 12, 22)),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
