# Generated by Django 4.2.7 on 2024-02-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(default='xyz@gmail.com', max_length=254)),
                ('floor', models.IntegerField()),
                ('resources', models.CharField(max_length=25)),
            ],
        ),
    ]
