# Generated by Django 5.0 on 2024-01-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_ppos_ssos_stockreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreport',
            name='ref_id',
        ),
    ]
