# Generated by Django 5.0 on 2024-02-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
