# Generated by Django 4.1.13 on 2024-02-10 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_myuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="role",
        ),
    ]
