# Generated by Django 4.1.13 on 2024-02-10 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_myuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="role",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.PROTECT, to="app.role"
            ),
        ),
    ]
