# Generated by Django 4.1.13 on 2024-02-28 06:59

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app", "0002_parentmodel_childmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proxymodel",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app.childmodel",),
        ),
    ]
