# Generated by Django 4.2.7 on 2023-12-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricketer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('age', models.IntegerField(max_length=2, null=True)),
                ('phone_no', models.IntegerField(max_length=10, null=True)),
                ('images', models.ImageField(upload_to='')),
                ('vedio', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
