# Generated by Django 4.2.7 on 2023-12-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cricketer_age_alter_cricketer_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketer',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='cricketer',
            name='vedio',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/'),
        ),
    ]
