# Generated by Django 4.2.7 on 2023-12-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cricketer_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cricketer',
            old_name='vedio',
            new_name='video',
        ),
    ]
