# Generated by Django 4.2.7 on 2023-12-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_vedio_cricketer_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketer',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
