# Generated by Django 4.2.7 on 2023-12-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cricketer_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketer',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
