# Generated by Django 5.0 on 2024-01-05 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_details',
            field=models.ManyToManyField(blank=True, to='testapp.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_details',
            field=models.ManyToManyField(blank=True, to='testapp.salesorder'),
        ),
        migrations.CreateModel(
            name='productcost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.product')),
            ],
        ),
    ]
