# Generated by Django 4.2.7 on 2024-01-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsalesorder',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productsalesorder',
            name='salesorder_id',
        ),
        migrations.DeleteModel(
            name='ProductPurachaseOrder',
        ),
        migrations.DeleteModel(
            name='ProductSalesOrder',
        ),
    ]
