# Generated by Django 4.2.7 on 2024-01-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_productsalesorder_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='costprice',
        ),
        migrations.CreateModel(
            name='CostPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='api.product')),
                ('sellingprice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost', to='api.product')),
            ],
        ),
    ]
