# Generated by Django 4.2.7 on 2024-01-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_cost_product_costprice_costprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costprice',
            name='sellingprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='costprice',
        ),
        migrations.AddField(
            model_name='costprice',
            name='costprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
