# Generated by Django 4.2.7 on 2024-01-05 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_costprice_sellingprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costprice',
            old_name='costprice',
            new_name='cost',
        ),
        migrations.AlterField(
            model_name='costprice',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product'),
        ),
    ]
