# Generated by Django 4.2.4 on 2023-12-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.BigIntegerField(default=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_ID', models.EmailField(max_length=100)),
                ('phone_No', models.BigIntegerField()),
                ('graduation', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=10)),
                ('grad_yop', models.IntegerField()),
                ('post_graduation', models.CharField(max_length=100)),
                ('Pg_Stream', models.CharField(blank=True, max_length=100, null=True)),
                ('Pg_Passed_Out_Year', models.IntegerField(blank=True, null=True)),
                ('Trained_On_Technology', models.CharField(max_length=100)),
                ('Institute_Name', models.CharField(max_length=250)),
                ('Duration_of_course', models.IntegerField()),
                ('Reference_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('hear_about_the_interview', models.CharField(max_length=250)),
                ('Experience', models.IntegerField(blank=True, null=True)),
                ('Previous_company_Name', models.CharField(max_length=250)),
                ('Current_CTC', models.IntegerField(blank=True, null=True)),
                ('Expected_CTC', models.IntegerField(blank=True, null=True)),
                ('PF_in_Last_Company', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
