# Generated by Django 4.2.4 on 2023-12-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='application_no',
            field=models.BigIntegerField(default=100),
        ),
    ]
