# Generated by Django 4.2.4 on 2023-12-19 10:55

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_aspirant_current_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='Current_CTC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='Duration_of_course',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='Expected_CTC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='Institute_Name',
            field=models.CharField(max_length=250, validators=[app1.models.only_alp]),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='PF_in_Last_Company',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='Pg_Passed_Out_Year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='Pg_Stream',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='application_no',
            field=models.BigIntegerField(default=app1.models.get_next_application_no),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='grad_yop',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='phone_No',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='post_graduation',
            field=models.CharField(max_length=100),
        ),
    ]
