# Generated by Django 4.2.7 on 2024-02-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='pincode',
            field=models.IntegerField(max_length=25),
        ),
    ]
