# Generated by Django 4.1 on 2023-12-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadhar',
            field=models.BigIntegerField(default=12356478956432),
            preserve_default=False,
        ),
    ]
