# Generated by Django 4.1 on 2023-12-10 13:53

import application.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_customer_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='value_less_zero',
            field=application.models.NegativeIntegerField(default=-1),
        ),
    ]
