# Generated by Django 4.1 on 2023-12-10 14:09

import application.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_customer_value_less_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name_upper',
            field=application.models.UppercaseField(default='', max_length=250),
        ),
    ]
