# Generated by Django 4.1 on 2023-12-10 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_customer_name_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='min_value_id',
            field=models.SmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(limit_value=25, message='value should greater than zero')]),
        ),
    ]
