# Generated by Django 5.0 on 2023-12-18 04:29

import datetime
import django.core.validators
import django.db.models.deletion
import re
import testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('validate_phone_number', models.SmallIntegerField(validators=[testapp.models.validate_phoneNum])),
                ('address', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('tech_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Atendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('check_in', models.TimeField(default=datetime.time(9, 59, 15, 735334))),
                ('check_out', models.TimeField()),
                ('status', models.CharField(max_length=1)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Tech_Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.employee')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testapp.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.technology')),
            ],
        ),
    ]
