# Generated by Django 5.0 on 2023-12-18 06:51

import datetime
import testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_daily_atendance_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_atendance',
            name='check_in',
            field=models.TimeField(default=datetime.time(12, 21, 38, 848916)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='validate_phone_number',
            field=models.BigIntegerField(validators=[testapp.models.validate_phoneNum]),
        ),
    ]
