# Generated by Django 5.0 on 2023-12-18 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_daily_atendance_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_atendance',
            name='check_in',
            field=models.TimeField(default=datetime.time(12, 35, 29, 934764)),
        ),
    ]
