# Generated by Django 5.0 on 2023-12-18 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_daily_atendance_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_atendance',
            name='check_in',
            field=models.TimeField(default=datetime.time(13, 0, 6, 786995)),
        ),
        migrations.AlterField(
            model_name='daily_atendance',
            name='date',
            field=models.DateField(),
        ),
    ]
