# Generated by Django 5.0 on 2023-12-18 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_daily_atendance_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_atendance',
            name='check_in',
            field=models.TimeField(default=datetime.time(14, 17, 31, 380019)),
        ),
    ]
