# Generated by Django 5.0 on 2023-12-18 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_daily_atendance_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_atendance',
            name='check_in',
            field=models.TimeField(default=datetime.time(15, 6, 0, 675729)),
        ),
    ]
