from django.db import models

# Create your models here.
class aspirant(models.Model):
    # application_no = models.BigIntegerField(unique=True, default=100)
    first_name = models.CharField(max_length=100, )
    last_name = models.CharField(max_length=100,)
    email_ID = models.EmailField(max_length = 100)
    phone_No = models.BigIntegerField()
    graduation = models.CharField(max_length =100, )
    stream = models.CharField(max_length =10,)
    grad_yop = models.IntegerField()
    post_graduation = models.CharField(max_length=100,)
    Pg_Stream = models.CharField(max_length=100,null= True, blank = True,)
    Pg_Passed_Out_Year = models.IntegerField(null= True, blank = True)
    Trained_On_Technology = models.CharField(max_length=100)
    Institute_Name = models.CharField(max_length=250)
    Duration_of_course = models.IntegerField()
    Reference_Name = models.CharField(max_length=100,null= True, blank = True)
    hear_about_the_interview = models.CharField(max_length=250)
    Experience = models.IntegerField(null= True, blank = True)
    Previous_company_Name = models.CharField(max_length= 250)
    Current_CTC = models.IntegerField(null= True, blank = True)
    Expected_CTC = models.IntegerField(null= True, blank = True)
    PF_in_Last_Company = models.BigIntegerField(null= True, blank = True)
    timestamp = models.DateTimeField(auto_now_add=True)