version: '3.8'
 
services:
  
  web:
    container_name: django_container
    build:
      context: .
      
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8001:8000"  
    depends_on:
      - db  
    
    environment:
      - DB_HOST=db
      - DB_NAME=ajadocker
      - DB_USER=root
      - DB_PASSWORD=root
 

  db:
    container_name: mysql_container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"


  nginx:
    container_name: nginx_container
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "81:80"  
    depends_on:
      - web  