# Generated by Django 5.0 on 2024-01-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=250)),
                ("Description", models.TextField()),
                ("Completed", models.BooleanField()),
                ("Created_at", models.DateTimeField()),
            ],
        ),
    ]
