# Generated by Django 4.1.13 on 2024-02-29 08:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="details",
            old_name="resouses",
            new_name="resourses",
        ),
        migrations.AlterField(
            model_name="details",
            name="email",
            field=models.EmailField(
                max_length=254, validators=[app.models.emailValidate]
            ),
        ),
    ]
