# Generated by Django 4.1.13 on 2024-02-29 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_resouses_details_resourses_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="details",
            old_name="resourses",
            new_name="resources",
        ),
    ]
