# Generated by Django 4.1.13 on 2024-02-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("common_field", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ChildModel",
            fields=[
                (
                    "parentmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.parentmodel",
                    ),
                ),
                ("specific_field", models.CharField(max_length=100)),
            ],
            bases=("app.parentmodel",),
        ),
    ]
