# Generated by Django 4.1.13 on 2024-02-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_parentmodel_childmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentmodel",
            name="age",
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
