# Use an official Nginx image as a parent image
FROM nginx

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/

# Expose port 80 to the Docker host, so you can access it from the outside
EXPOSE 80
